spring:
  application:
    name: job_tracker
    version: 0.0.1
  jackson:
    time-zone: America/Bogota
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/job_tracker
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
